###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "user-3-1",
  "password": "123456"
}

###
GET http://localhost:8080/api/secured-facilities
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyLTMtMSIsImV4cCI6MTYyOTQ5MzIwMH0.4m6Oz8S9tkg6bY8GgjhV1sGCNmcurKrcdQ4QilZs9aYY5aBV5ERVrji2kSmNg5m3j9YabdkzsPDY_U-AfOTy1Q

###
POST http://localhost:8080/api/secured-facilities
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyLTQtMSIsImV4cCI6MTYyOTQwNjgwMH0.wwy_0G1kYuPUDxBLkdbRDOVplmB5ZtuJiRVdRqEw8OjuAcTA2yMrCeZ1E4fZtOD4YtMCgMLey8qX_t2mxaOokg
Content-Type: application/json

{
  "id": 88,
  "name": "test",
  "itn": "test",
  "ownerId": 5
}

###
PUT http://localhost:8080/api/secured-facilities
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyLTQtMSIsImV4cCI6MTYyOTQwNjgwMH0.wwy_0G1kYuPUDxBLkdbRDOVplmB5ZtuJiRVdRqEw8OjuAcTA2yMrCeZ1E4fZtOD4YtMCgMLey8qX_t2mxaOokg
Content-Type: application/json

{
  "id": 1,
  "name": "wtf!!!1",
  "itn": "dudea1",
  "ownerId": 2
}

###
DELETE http://localhost:8080/api/secured-facilities/1
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyLTQtMSIsImV4cCI6MTYyOTQwNjgwMH0.wwy_0G1kYuPUDxBLkdbRDOVplmB5ZtuJiRVdRqEw8OjuAcTA2yMrCeZ1E4fZtOD4YtMCgMLey8qX_t2mxaOokg

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
POST http://localhost:8080/api/commits/111111111111111/RFID3/1/

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "firstName": "admin",
  "lastName": "admin",
  "personnelNumber": 0,
  "position": "Админ",
  "phone": "+79008007060",
  "timezone": "Europe/Moscow",
  "isLead": true
}



